id: IFCC22BB2
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T13:15:49+00:00'
last_modified: '2022-06-15T17:38:37.449011+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG22269
  title: ལྷ་མོའི་ཟློས་གར་གྱི་འཁྲབ་གཞུང་དྭངས་ཤེལ་མེ་ལོང་།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    69D3:
      image_group_id: I1KG22317
      title: Volume 1 of lha mo'i zlos gar gyi 'khrab gzhung dwangs shel me long /
      total_pages: 196
      order: 1
      base_file: 69D3.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
